export const FREE_MULTISEARCH_CARD_LIMIT = 10;

export const DISCOUNT_MAP = {
  HOCSNAPCASTER: 0.05,
  'OBSIDIAN+SNAPCASTER5': 0.05,
  'SNAPCASTER-D24': 0.07
};

export const SEALED_DISCOUNT_MAP = {
  'OBSIDIAN+SNAPCASTER5': 0.05
};
